spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/ai_diviner
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      password: root
  web:
    resources:
      add-mappings: false

server:
  port: 232
  servlet:
    encoding:
      force: true